// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAaxPScFy6YWiFQYTRZzJtV_ekq64RZZ4',
    appId: '1:1083109793751:web:51679ccbb6f94e95093592',
    messagingSenderId: '1083109793751',
    projectId: 'cermatify',
    authDomain: 'cermatify.firebaseapp.com',
    storageBucket: 'cermatify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-hE_vK-jHrmvcpEGq9oteu1UTMgZft4',
    appId: '1:1083109793751:android:e40aa399ae70144a093592',
    messagingSenderId: '1083109793751',
    projectId: 'cermatify',
    storageBucket: 'cermatify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_daplNNh5PNRoY_VZGR66hj942Orx7uA',
    appId: '1:1083109793751:ios:f41185c43cc2b0a2093592',
    messagingSenderId: '1083109793751',
    projectId: 'cermatify',
    storageBucket: 'cermatify.firebasestorage.app',
    iosBundleId: 'com.example.cermatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_daplNNh5PNRoY_VZGR66hj942Orx7uA',
    appId: '1:1083109793751:ios:f41185c43cc2b0a2093592',
    messagingSenderId: '1083109793751',
    projectId: 'cermatify',
    storageBucket: 'cermatify.firebasestorage.app',
    iosBundleId: 'com.example.cermatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAaxPScFy6YWiFQYTRZzJtV_ekq64RZZ4',
    appId: '1:1083109793751:web:ace872e37247dc0d093592',
    messagingSenderId: '1083109793751',
    projectId: 'cermatify',
    authDomain: 'cermatify.firebaseapp.com',
    storageBucket: 'cermatify.firebasestorage.app',
  );
}
